from os import getenv

STORAGE_TYPE=getenv('STORAGE_TYPE')
STORAGE_HOST=getenv('STORAGE_HOST')
STORAGE_PORT=getenv('STORAGE_PORT')
STORAGE_USERNAME=getenv('STORAGE_USERNAME')
STORAGE_PASSWORD=getenv('STORAGE_PASSWORD')
SALT=getenv('SALT')
VERSION="v0.0.1"
