steps:
  - name: build
    image: docker
    environment:
      REGISTRY_USER:
        from_secret: REGISTRY_USER
      REGISTRY_KEY:
        from_secret: REGISTRY_KEY
      REGISTRY: git.cadred.ru
    commands:
      - docker login -u $REGISTRY_USER -p $REGISTRY_KEY $REGISTRY
      - docker compose build
      - docker compose push

when:
  - branch: deployment
    event: [manual, push]
