steps:
  - name: deploy
    image: git.cadred.ru/chilyumov_fedor/ssh-plugin
    pull: true
    settings:
      ssh_host:
        from_secret: SSH_HOST
      ssh_user:
        from_secret: SSH_USER
      ssh_key:
        from_secret: SSH_KEY
      registry: git.cadred.ru
      registry_key:
        from_secret: REGISTRY_KEY
      registry_user: 
        from_secret: REGISTRY_USER
      script: |
        docker compose pull
        docker compose up -d

    when:
      - branch: deployment 
        event: [manual, push]

depends_on:
  - build
